name: dating_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+8

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sailor: ^0.7.1
  bot_toast: ^4.0.1
  flutter_screenutil: ^5.0.0+2
  font_awesome_flutter: ^9.0.0-nullsafety
  flutter_staggered_animations: ^1.0.0
  flutter_animator: ^3.1.1
  flutter_staggered_grid_view: ^0.4.0
  intl: ^0.17.0
  im_animations: ^0.1.1
  flutter_swiper: ^1.1.6
  percent_indicator: ^3.0.1
  dio: ^4.0.1
  image_picker: ^0.8.2
  cached_network_image: ^3.1.0
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.6
  device_info_plus: ^2.1.0
  provider: ^5.0.0
  firebase: ^9.0.0
  firebase_core_web: ^1.1.0
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.1
  firebase_auth_web: ^3.1.0
  google_maps_flutter: ^2.1.1

  geocoding:
  geolocator:

 
  lottie: ^1.2.1
  feather_icons: ^1.0.1
  animated_text_kit: ^4.2.1
  permission_handler: ^6.0.1
  animated_bottom_navigation_bar: ^0.3.1
  day_night_time_picker: ^1.0.3+1
  device_preview: ^0.7.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.1
  pinput: ^1.2.0
  socket_io_client: ^1.0.1
  firebase_messaging: ^10.0.8
  flutter_local_notifications: ^9.0.0
  gradient_ui_widgets: ^1.0.2-nullsafety
  photo_view: ^0.13.0
  share: ^2.0.4
  firebase_dynamic_links: ^2.0.11
  flutter_facebook_auth: ^3.3.3-no-nullsafety
  flutter_webview_plugin: ^0.4.0
  sticky_grouped_list: ^1.3.0
  google_mobile_ads: ^0.13.6
  cryptography: ^2.0.4
  razorpay_flutter: ^1.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/fonts/
     - assets/images/
     - assets/icons/
     - assets/lottie/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf

    - family: lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
